//User ASK
export const GET_ASKLIST = "GET_ASKLIST";
export const GET_ASK = "GET_ASK";
export const ADD_ASK = "ADD_ASK";
export const ASK_ERROR = "ASK_ERROR";
export const ASK_UNLOADED = "ASK_UNLOADED";
export const ASKLIST_UNLOADED = "ASKLIST_UNLOADED";
export const ASK_ISANSWER = "ASK_ISANSWER";
//User ROOM
export const GET_ROOMLIST = "GET_ROOMLIST";
export const GET_ROOM = "GET_ROOM";
export const JOIN_ROOM = "JOIN_ROOM";
export const LEAVE_ROOM = "LEAVE_ROOM";
export const ROOM_ERROR = "ROOM_ERROR";
export const ROOM_UNLOADED = "ROOM_UNLOADED";
export const ROOMLIST_UNLOADED = "ROOMLIST_UNLOADED";
//User QUESTION
export const GET_QUESTIONLIST = "GET_QUESTIONLIST";
export const GET_QUESTION = "GET_QUESTION";
export const QUESTION_ERROR = "QUESTION_ERROR";
export const QUESTION_UNLOADED = "QUESTION_UNLOADED";
export const QUESTIONLIST_UNLOADED = "QUESTIONLIST_UNLOADED";
//Organizer ASK
export const GET_ORG_ASKLIST = "GET_ORG_ASKLIST";
export const GET_ORG_ASK = "GET_ORG_ASK";
export const ORG_ASK_ERROR = "ORG_ASK_ERROR";
export const ORG_ASK_UNLOADED = "ORG_ASK_UNLOADED";
export const ORG_ASKLIST_UNLOADED = "ORG_ASKLIST_UNLOADED";
//Organizer ROOM
export const GET_ORG_ROOMLIST = "GET_ORG_ROOMLIST";
export const GET_ORG_ROOM = "GET_ORG_ROOM";
export const CREATE_ROOM = "CREATE_ROOM";
export const DELETE_ROOM = "DELETE_ROOM";
export const EDIT_ROOM = "EDIT_ROOM";
export const EDIT_ASK_STATUS = "EDIT_ASK_STATUS";
export const EDIT_FEEDBACK_STATUS = "EDIT_FEEDBACK_STATUS";
export const ORG_ROOM_ERROR = "ORG_ROOM_ERROR";
export const ORG_ROOM_UNLOADED = "ORG_ROOM_UNLOADED";
export const ORG_ROOMLIST_UNLOADED = "ORG_ROOMLIST_UNLOADED";
//Organizer FEEDBACK
export const GET_ORG_FEEDBACKLIST = "GET_ORG_FEEDBACKLIST";
export const GET_ORG_FEEDBACK = "GET_ORG_FEEDBACK";
export const ORG_FEEDBACK_ERROR = "ORG_FEEDBACK_ERROR";
export const ORG_FEEDBACK_UNLOADED = "ORG_FEEDBACK_UNLOADED";
export const ORG_FEEDBACKLIST_UNLOADED = "ORG_FEEDBACKLIST_UNLOADED";
//Feedback
export const GET_FEEDBACKLIST = "GET_FEEDBACKLIST";
export const GET_FEEDBACK = "GET_FEEDBACK";
export const ADD_FEEDBACK = "ADD_FEEDBACK";
export const FEEDBACK_ERROR = "FEEDBACK_ERROR";
export const FEEDBACK_UNLOADED = "FEEDBACK_UNLOADED";
export const FEEDBACKLIST_UNLOADED = "FEEDBACKLIST_UNLOADED";
//Organizer QUESTION
export const CREATE_QUESTION = "CREATE_QUESTION";
export const GET_ORG_QUESTIONLIST = "GET_ORG_QUESTIONLIST";
export const GET_ORG_QUESTION = "GET_ORG_QUESTION";
export const ORG_QUESTION_ERROR = "ORG_QUESTION_ERROR";
export const ORG_QUESTION_UNLOADED = "ORG_QUESTION_UNLOADED";
export const ORG_QUESTIONLIST_UNLOADED = "ORG_QUESTIONLIST_UNLOADED";
export const DELETE_QUESTION = "DELETE_QUESTION";
export const EDIT_QUESTION = "EDIT_QUESTION";
//Organizer ANSWER
export const GET_ORG_ANSWERLIST = "GET_ORG_ANSWERLIST";
export const GET_ORG_ANSWER = "GET_ORG_ANSWER";
export const ORG_ANSWER_ERROR = "ORG_ANSWER_ERROR";
export const ORG_ANSWER_UNLOADED = "ORG_ANSWER_UNLOADED";
export const ORG_ANSWERLIST_UNLOADED = "ORG_ANSWERLIST_UNLOADED";
//Answer
export const GET_ANSWERLIST = "GET_ANSWERLIST";
export const GET_ANSWER = "GET_ANSWER";
export const ADD_ANSWER = "ADD_ANSWER";
export const ANSWER_ERROR = "ANSWER_ERROR";
export const ANSWER_UNLOADED = "ANSWER_UNLOADED";
export const ANSWERLIST_UNLOADED = "ANSWERLIST_UNLOADED";
//Auth
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const TOKEN_LOADED = "TOKEN_LOADED";
export const LOGOUT = "LOGOUT";
//Alert
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";
